#!/usr/bin/env bash

# Defaults

default_artist="Gentleman"
default_album="House Mixes"
default_album_artist="Various"

# Form

echo
echo "Download and convert a YouTube video to an MP3 file."
echo

read -p "URL: " url
read -p "Title: " title
read -p "Artist [$default_artist]: " artist
read -p "Album [$default_album]: " album
read -p "Album artist [$default_album_artist]: " album_artist

artist=${artist:-$default_artist}
album=${album:-$default_album}
album_artist=${album_artist:-$default_album_artist}

file_name="$HOME/Music/$artist - $title"


# Download audio from video URL

echo
echo "Downloading and converting. Please wait..."
echo

yt-dlp \
	--force-overwrites \
	--extract-audio \
	--format bestaudio \
	--audio-format mp3 \
	--output "$file_name.tmp.%(ext)s" \
	"$url" \
	1> /dev/null

# Add metadata

ffmpeg \
	-loglevel error \
	-y \
	-i "$file_name.tmp.mp3" \
	-metadata title="$title" \
	-metadata artist="$artist" \
	-metadata album_artist="$album_artist" \
	-metadata album="$album" \
	"$file_name.mp3" \
	1> /dev/null

# Remove temporary file

rm "$file_name.tmp.mp3"

# Complete

echo "Download and conversion complete."
echo
echo "Your music file is here: $file_name.mp3"
echo