#!/usr/bin/env bash

# Summary

echo
echo "Download and convert a YouTube video to an MP3 file."
echo


# Form

echo -n "YouTube video URL: "
read -r youtube_video_url

echo -n "Track title: "
read -r title

echo -n "Lead artist: "
read -r artist

echo -n "Album-level artist: "
read -r album_artist

echo -n "Album name: "
read -r album

echo -n "Release date or year: "
read -r date

echo -n "Track number: "
read -r track

echo -n "Genre: "
read -r genre

file_name="$HOME/Music/$artist - $title"

echo
echo "Downloading and converting. Please wait..."
echo


# Extract audio from YouTube video and save to temporary file

yt-dlp \
	--force-overwrites \
	--extract-audio \
	--format bestaudio \
	--audio-format mp3 \
	--output "$file_name.tmp.%(ext)s" \
	"$youtube_video_url" \
	1> /dev/null


# Add metadata and save converted audio file

ffmpeg \
	-loglevel error \
	-y \
	-i "$file_name.tmp.mp3" \
	-metadata title="$title" \
	-metadata artist="$artist" \
	-metadata album_artist="$album_artist" \
	-metadata album="$album" \
	-metadata date="$date" \
	-metadata track="$track" \
	-metadata genre="$genre" \
	"$file_name.mp3" \
	1> /dev/null


# Remove temporary audio file

rm "$file_name.tmp.mp3"


# Final message

echo "Download and conversion complete!"
echo
echo "Your music file is here: $file_name.mp3"
echo

